services:
  jekyll:
    platform: linux/amd64
    image: jekyll/jekyll:4
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --force_polling --drafts
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle/:/usr/local/bundle
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3